name: Test and coverage
on: [push, pull_request]
jobs:
  build:
    name: Test coverage
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: setup-go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'
      - name: Run tests
        run: | 
          make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
