name: e2e-test
on: [push, pull_request]
jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: 1.23
      id: go
    - name: checkout project
      uses: actions/checkout@v3
    - name: start minikube
      uses: manusa/actions-setup-minikube@v2.13.1
      with:
        minikube version: 'v1.33.1'
        kubernetes version: 'v1.33.3'
        driver: 'docker'
    - name: configure Minikube
      run: |
        minikube addons enable ingress
        config/hack/modify_etc_hosts.sh "keycloak.local"
    - name: e2e tests
      run: |
        echo KUBECONFIG $KUBECONFIG
        ls ~ -la
        make install
        echo "install finished ====================================================="
        make installKeycloak
        echo "installKeycloak finished ====================================================="
        kubectl get ingress -A 
        echo "getIngress finished ====================================================="
        make test/e2e
        echo "test/e2e ====================================================="
